language: php
php:
  - 5.5
  - hhvm
services:
  - mysql
  - couchdb
  - redis
before_script:
  - source src/etc/travis.conf
  - mysql -e 'create database $PDO_DB;'
  - mysql -u $PDO_USERNAME $PDO_DB < src/sql/struct.sql
install:
  - composer install
script: composer test